### ISSUE TITLE
Убрать вращение камеры из-за вращения родителя

### ISSUE THREAD

**Issue by Fedor-Lyanguzov** [kisate/Space-Sim#5]
Теоретически, можно использовать `base.camera.lookAt(self.Earth)`, где `self.Earth` - нужный нам объект. Надо попробовать, а там посмотрим.
https://www.panda3d.org/forums/viewtopic.php?t=5622

**Comment by kisate** [comment]
Проблема в том, что камера в этом случае смотрит на фиксированную точку планеты, а так как та вращается, то и камера вместе с ней
